boot.o: boot.S multiboot.h x86_desc.h types.h
x86_desc.o: x86_desc.S x86_desc.h types.h
filesystem.o: filesystem.c filesystem.h lib.h types.h
i8259.o: i8259.c i8259.h types.h lib.h synch.h
idt.o: idt.c x86_desc.h types.h lib.h idt.h
kernel.o: kernel.c multiboot.h types.h x86_desc.h lib.h i8259.h debug.h \
  tests.h idt.h drivers/keyboard.h drivers/rtc.h
lib.o: lib.c lib.h types.h
synch.o: synch.c synch.h lib.h types.h
tests.o: tests.c tests.h x86_desc.h types.h lib.h
keyboard.o: drivers/keyboard.c drivers/../lib.h drivers/../types.h \
  drivers/../synch.h drivers/../idt.h drivers/../x86_desc.h \
  drivers/../i8259.h drivers/keyboard.h
rtc.o: drivers/rtc.c drivers/../lib.h drivers/../types.h \
  drivers/../synch.h drivers/../idt.h drivers/../x86_desc.h drivers/rtc.h \
  drivers/../tests.h drivers/../i8259.h
